---
- name: configure WSL
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
  - name: ensure aptitude is installed
    command: apt-get -y install aptitude warn=False

  - name: update apt
    apt:
      update_cache: yes
      upgrade: safe
  
  - name: upgrade packages
    apt: upgrade=yes

  - name: Install list of packages
    apt: 
      name: [jq, vim, curl]
      state: present
  
  - name: Install terraform
    become: yes
    command: echo ; zcat <( CURRR_VER=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version') ; curl -q "https://releases.hashicorp.com/terraform/${CURRR_VER#?}/terraform_${CURRR_VER#?}_linux_amd64.zip" ) | sudo tee /usr/local/bin/terraform > /dev/null ; sudo chmod +x /usr/local/bin/terraform

