---

- name: Load "{{ ansible_system }} OS family variables.
  include_vars: "{{ ansible_system }}.yml"

- name: Ensure required packages are available.
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ terraform_dep_packages }}"


- name: Ensure install directory is available.
  file:
    path: "{{ terraform_install_dir }}"
    mode: 0755
    state: directory

- name: "Download terraform {{ terraform_version }} binary."
  command: wget {{ terraform_download_url }} --directory-prefix=/tmp/ warn=False

- name: "Unarchive terraform {{ terraform_version }} zip."
  unarchive:
    copy: no
    src:  "/tmp/terraform_{{ terraform_version }}_{{ ansible_system | lower }}_amd64.zip"
    dest: "{{ terraform_install_dir }}"
    creates: "{{ terraform_install_dir }}/terraform"
    mode: 0755

- name: Set symlink to /usr/local/bin/terraform.
  file:
    state: link
    src: "/usr/local/share/terraform/{{ terraform_version }}/terraform"
    dest: "/usr/local/bin/terraform"
