---
- name: configure WSL
  hosts: 127.0.0.1
  connection: local
  become: yes
  vars:
    terraform_version: "0.11.11"
  tasks:
  - name: check if aptitude is installed
    shell: dpkg-query -W -f='${Status}' aptitude | grep 'install ok installed'
    register: aptitude_installed
    failed_when: no
    changed_when: no

  - name: ensure aptitude is installed
    command: apt-get -y install aptitude warn=False
    when: aptitude_installed.rc == 0

  - name: update apt
    apt:
      update_cache: yes
      upgrade: safe
    register: task_result
    until: task_result.rc == 0
    retries: 3
    delay: 10

  - name: upgrade packages
    apt: upgrade=yes
    register: task_result
    until: task_result.rc == 0
    retries: 3
    delay: 10

  - name: Install list of packages
    apt:
      name: [jq, vim, curl, unzip, dnsutils]
      state: present
    register: task_result
    until: task_result.rc == 0
    retries: 3
    delay: 10

  roles:
    - terraform
