- name: Register OS Distribution ID
  command: lsb_release -is
  register: distro

- name: Register OS Codename
  command: lsb_release -cs
  register: codename

- name: update apt
  apt:
    update_cache: yes
    upgrade: safe
  register: task_result
  until: task_result is success
  retries: 3
  delay: 10

- name: Install list of dependencies
  apt:
    name: [apt-transport-https, ca-certificates, curl, gnupg2, software-properties-common]
    state: present
  register: task_result
  until: task_result is success
  retries: 3
  delay: 10

- name: Add an Apt signing key from Docker
  apt_key:
    url: https://download.docker.com/linux/{{ distro.stdout|lower }}/gpg
    state: present

- name: Add Apt repository for Docker
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ distro.stdout|lower }} {{ codename.stdout }} stable
    state: present

- name: update apt
  apt:
    update_cache: yes
    upgrade: safe
  register: task_result
  until: task_result is success
  retries: 3
  delay: 10

- name: Install docker dependencies from non-free/contrib
  apt:
    name: [zfsutils-linux, cgroup-bin, cgroup-tools, cgroupfs-mount, libcgroup1]
    state: present
  register: task_result
  until: task_result is success
  retries: 3
  delay: 10

- name: Install docker
  apt:
    name: [docker-ce, docker-ce-cli, containerd.io]
    state: present
  register: task_result
  until: task_result is success
  retries: 3
  delay: 10

- name: Make sure we have a 'docker' group
  group:
    name: docker
    state: present

- name: Add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"

- name: Start service docker, if not started
  service:
    name: docker
    state: started